# site properties and page defaults
title: Korthauer Lab
subtitle: Statistics + Genomics
description: We work on advancing statistical methodology and computational tools for the analysis of high-dimensional genomics data. With these tools, we aim to uncover new molecular signals in cancer, child health, and development.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: keegan.korthauer@ubc.ca
  orcid: 0000-0002-4565-1654
  google-scholar: spd-KjUAAAAJ
  github: korthauer-lab
  mastodon-genomicsocial: keegankorthauer
  bluesky: keegankorthauer
  
### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
