- id: doi:10.48550/arXiv.2308.02067
  date: '2023-08-03'
  image: https://github.com/giulianonetto/bayesdca/raw/master/man/figures/README-unnamed-chunk-5-1.png
  buttons:
    - type: source
      link: https://github.com/giulianonetto/paper-bayesdca
    - type: package
      text: R Package
      link: https://github.com/giulianonetto/bayesdca
      
- id: doi:10.1101/381145 
  image: images/reanalysis.gif
  buttons:
    - type: source
      link: https://github.com/kdkorthauer/repressiveCapacity

- id: doi:10.1016/j.nbd.2023.106138
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0969996123001523-gr5.jpg
  buttons: 
    - type: source
      link: https://github.com/ErickNavarroD/hum_progranulin_RNAseq_Leavitt

- id: doi:10.1186/s13059-023-02869-1
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs13059-023-02869-1/MediaObjects/13059_2023_2869_Fig1_HTML.png
  buttons: 
    - type: source
      link: https://github.com/kdkorthauer/rat_imprintome
      
- id: doi:10.1172/JCI151666
  image: https://dm5migu4zj3pb.cloudfront.net/manuscripts/151000/151666/medium/JCI151666.f1.jpg
  buttons: 
    - type: source
      link: https://github.com/kdkorthauer/MCC
      
- id: doi:10.1158/1078-0432.CCR-21-3762
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/28/5/10.1158_1078-0432.ccr-21-3762/5/m_928fig1.jpeg?Expires=1697653199&Signature=rP3iDnbFSdo3Uf20wNEUzbTZvLwzKf1caGvwUAw9lG3-6NnSDUiozcX24SsBaZG04p5KP~I4f3i3oFrYHflMaaAD8CTgcZec7Zzab5nKCwkM3B3HUhPizrg1a1n6ENGRVWoNFASaZPZQbpwgYViDO0SPI2B7CLutU0Ljh2KSFEPq-IGq5CWend5jhm3CTrPVVn3lPepeVfnAVpZ1ZxXSxIktMiHRaSW4ByFcK59xdAnu4MO5rtJWp6F0W~bD5jq9FGQs~Qw46gyCkA~H4DJnqmmLGWzKSWMSLV0VeoG5bz8Nu4JG6JcD6oaMGTbbMFGHi4XY8CpYyYQ5j5lHydy9VA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA      
  buttons: 
      
- id: doi:10.1038/s41467-021-27077-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-021-27077-y/MediaObjects/41467_2021_27077_Fig1_HTML.png
  
- id: doi:10.1111/febs.15858
  image: https://febs.onlinelibrary.wiley.com/cms/asset/b5f3ef07-2a56-4c82-892f-22847fc2fde9/febs15858-fig-0001-m.png
  
- id: doi:10.1214/20-AOAS1423
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10275512/bin/nihms-1901161-f0005.jpg
  buttons:
    - type: package
      text: R package
      link: https://github.com/wiscstatman/scDDboost
      
- id: doi:10.1038/s41467-021-22139-7
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-021-22139-7/MediaObjects/41467_2021_22139_Fig5_HTML.png?as=webp
  
- id: doi:10.1038/s43018-020-00135-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43018-020-00135-y/MediaObjects/43018_2020_135_Fig1_HTML.png?as=webp

- id: doi:10.1038/s41586-020-2766-y
  image: https://media.springernature.com/w300/springer-static/image/art%3A10.1038%2Fs41591-020-01147-y/MediaObjects/41591_2020_1147_Figa_HTML.jpg?as=webp
  
- id: doi:10.1038/s41588-020-0664-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41588-020-0664-8/MediaObjects/41588_2020_664_Fig2_HTML.png?as=webp

- id: doi:10.1038/s41436-020-0801-x
  image: https://www.gimjournal.org/cms/attachment/ad6f4dc5-411f-4ca8-ad11-f98e860c9122/gr2.jpg

- id: doi:10.1038/s41591-020-0933-1
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41591-020-0933-1/MediaObjects/41591_2020_933_Fig1_HTML.png?as=webp
  buttons:
    - type: source
      link: https://github.com/kdkorthauer/cfMeDIPseq-RCC

- id: doi:10.1093/biostatistics/kxy007
  date: '2019-07-01'
  image: images/dmrseqimage.jpeg
  buttons:
    - type: source
      link: https://github.com/kdkorthauer/dmrseqPaper
    - type: package
      text: R/Bioconductor package
      link: https://www.bioconductor.org/packages/release/bioc/html/dmrseq.html

- id: doi:10.1186/s13059-019-1716-1
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs13059-019-1716-1/MediaObjects/13059_2019_1716_Fig6_HTML.png
  buttons: 
    - type: source
      link: https://github.com/pkimes/benchmark-fdr
    - type: package
      text: Data package
      link: https://bioconductor.org/packages/release/data/experiment/html/benchmarkfdrData2019.html
    - type: package
      text: Shiny app
      link: https://github.com/kdkorthauer/benchmarkfdr-shiny
  
- id: doi:10.1016/j.cell.2018.05.037
  image: https://www.cell.com/cms/attachment/b6b454a0-c30b-403a-81d1-a6dfdd5cb91f/fx1.jpg
  
- id: doi:10.15252/embj.201798452
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5852646/bin/EMBJ-37-e98452-g002.jpg
  
- id: doi:10.1007/s12561-016-9144-1
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5617361/bin/nihms810073f1.jpg

- id: doi:10.1186/s13059-016-1077-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs13059-016-1077-y/MediaObjects/13059_2016_1077_Fig3_HTML.gif?as=webp

- id: doi:10.1093/carcin/bgv171
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4834967/bin/carcin_bgv171_f0002.jpg
  
- id: doi:10.1093/bioinformatics/btu858
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4426832/bin/btu858f1p.jpg
  
- id: doi:10.1002/gepi.21820
  image: https://onlinelibrary.wiley.com/cms/asset/f91a96ed-6bfa-4591-b826-a2ab6c2fee91/gepi21820-fig-0001-m.png
  
- id: doi:10.1017/cbo9781139226448.019
  image: https://assets.cambridge.org/97811070/27527/cover/9781107027527.jpg
  
- id: doi:10.1128/IAI.05326-11
  image: https://journals.asm.org/cms/10.1128/iai.05326-11/asset/c1cbe073-cabd-4bf2-a040-0045a3251c85/assets/graphic/zii9990995170001.jpeg

- id: doi:10.1094/mpmi-21-11-1408
  image: images/arabidopsisfig.png
  
- id: doi:10.1101/2023.11.20.567911
  image: https://github.com/nshen7/vmrseq/raw/main/man/figures/method.png
  buttons:
    - type: source
      link: https://github.com/nshen7/vmrseq-experiments
    - type: package
      text: R package
      link: https://github.com/nshen7/vmrseq
  
- id: doi:10.1101/655795
  type: duplicate

- id: doi:10.1101/189654
  type: duplicate
  
- id: doi:10.1101/035501
  type: duplicate
  
- id: doi:10.1097/WON.0B013E31821530CA
  type: duplicate

- id: doi:10.1101/2022.04.21.488764
  type: duplicate

- id: doi:10.1101/2020.10.23.350793
  type: duplicate

- id: doi:10.1038/s41591-020-1078-y
  type: duplicate
  
- id: doi:10.1200/JCO.2020.38.6_SUPPL.728
  type: duplicate

- id: doi:10.1200/jco.2020.38.15_suppl.5046
  type: duplicate
  
- id: doi:10.1101/2024.07.02.600461
  image: https://www.biorxiv.org/content/biorxiv/early/2024/09/28/2024.07.02.600461/F2.large.jpg

- id: doi:10.1101/2024.10.07.617116
  image: https://www.biorxiv.org/content/biorxiv/early/2024/10/11/2024.10.07.617116/F1.large.jpg